# Generated by Django 3.2.5 on 2022-03-12 02:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220311_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 2, 58, 18, 25930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='learn',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 2, 58, 18, 23929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 2, 58, 18, 24928, tzinfo=utc)),
        ),
    ]
