# Generated by Django 3.2.5 on 2022-03-13 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220312_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 3, 36, 48, 382083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='learn',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 3, 36, 48, 382083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 3, 36, 48, 382083, tzinfo=utc)),
        ),
    ]
